### ISSUE TITLE
Correção

### ISSUE THREAD

**Issue by EdiJunior88** [Prdsilva80/clipboard-lp#1]
Fala Paulo, tudo tranquilo? Passando aqui para te parabenizar pelo ótimo projeto, mas quero ressaltar alguns pontos

- O Footer não está totalmente alinhado ao final da página e fica esse espaço em branco
![Frontend-Mentor-Clipboard-Landing-Page](https://user-images.githubusercontent.com/13875907/212722432-f975ad73-9a72-4c2b-875a-7dbdac9b8ad6.jpg)

Na classe **footer**, se você colocar um **align-items: flex-end;** e vai ficar alinhado no fim da página, outra coisa se possível coloca em uma div "Pai" para a imagem e os textos do footer para não quebrar o layout quando for trabalhar na parte responsiva

- Erro ao abrir a imagem banner (404)
![Desktop-screenshot](https://user-images.githubusercontent.com/13875907/212722520-d9ac6c8c-d4eb-4727-938f-c50550214161.jpg)

**Comment by Prdsilva80** [comment]
Muito obrigado por compartilhar seu conhecimento comigo!! Pode deixar que
em breve farei as mudanças sugeridas por você!

Em seg., 16 de jan. de 2023 13:15, Edivaldo Junior ***@***.***>
escreveu:
